# Generated by Django 3.2.15 on 2022-09-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operator',
            table='well_logs_operator',
        ),
    ]
