# Generated by Django 3.2.15 on 2022-09-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0003_auto_20220908_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
        migrations.AlterModelTable(
            name='log',
            table=None,
        ),
        migrations.AlterModelTable(
            name='operator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='well',
            table=None,
        ),
    ]
