# Generated by Django 3.2.15 on 2022-09-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0004_auto_20220908_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-start_time',)},
        ),
        migrations.RemoveField(
            model_name='log',
            name='year',
        ),
        migrations.AddField(
            model_name='log',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
