# Generated by Django 3.2.15 on 2022-09-08 15:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0005_auto_20220908_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime.now)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime.now)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.datetime.now)]),
        ),
    ]
