# Generated by Django 3.2.15 on 2022-09-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0006_auto_20220908_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='scheduled',
        ),
    ]
